### ISSUE TITLE
我占个第一名

### ISSUE THREAD

**Issue by gogo03** [Tencent/Hunyuan3D-1#1]
^_^

**Comment by h3clikejava** [comment]
![image](https://github.com/user-attachments/assets/e0a18138-7737-41c0-8b3a-f9de74acbaa2)
来早了

**Comment by Wi-sc** [comment]
Thanks for your interest. The [huggingface link](https://huggingface.co/tencent/Hunyuan3D-1) has been fixed. Sorry for that.
