### ISSUE TITLE
https://huggingface.co/spaces/tencent/Hunyuan3D-1 [404 Error]

### ISSUE THREAD

**Issue by macanhhuy** [Tencent/Hunyuan3D-1#11]
It seems the page is not available now

**Comment by macanhhuy** [comment]
The correct one should be https://huggingface.co/tencent/Hunyuan3D-1

**Comment by Wi-sc** [comment]
Thanks for your interest. The [huggingface link](https://huggingface.co/tencent/Hunyuan3D-1) has been fixed. Sorry for that.
