### ISSUE TITLE
RuntimeError: CUDA error

### ISSUE THREAD

**Issue by yikexiaoxing** [Tencent/Hunyuan3D-1#12]
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

![image](https://github.com/user-attachments/assets/f946332a-bce6-427d-99a3-1fe5b4f207cb)

**Comment by AlextangQ19** [comment]
the same problem
<img width="988" alt="image" src="https://github.com/user-attachments/assets/a13a9eab-9272-4fcd-a3ee-d2fbc0021b48">

**Comment by yikexiaoxing** [comment]
我找到了原因，cuda版本不正确，python3.9+cuda118可以正确执行

**Comment by AlextangQ19** [comment]
> 我找到了原因，cuda版本不正确，python3.9+cuda118可以正确执行

嗯嗯实测py3.9 + torch2.2.0-cu118 ok的
