### ISSUE TITLE
Multi GPU Support?

### ISSUE THREAD

**Issue by psych0v0yager** [Tencent/Hunyuan3D-1#15]
Are there plans to support multiple GPUs. Currently when I run app.py (passing in --device cuda) I receive an OOM, even though my second GPU is completely empty

**Comment by psych0v0yager** [comment]
That’s unfortunate. At least the `—save-memory` option works pretty well on a 3090

**Comment by HuiwenShi** [comment]
Each module has its own device parameters, but to simplify usage, we only provide a global device parameter in main.py/app.py. To enable the execution of different modules on multiple GPUs, you can manually assign devices to each module. It is recommended to run the text-to-image and image-to-views modules on different GPUs for optimal performance.
