### ISSUE TITLE
请问：图生3D的指标项上限和效果最佳的值是多少

### ISSUE THREAD

**Issue by g711ab** [Tencent/Hunyuan3D-1#17]
max number of faces 和 Gen step 如何设置可以达到效果最佳？

![output (1)](https://github.com/user-attachments/assets/615822cf-62ef-4cb4-b69d-7723ec41a606)

obj效果优于instantMesh 和 TripoSR

**Comment by Wi-sc** [comment]
Thank you for your interest. I believe that both of these options are better when they are larger.
