### ISSUE TITLE
腾讯的开源项目请增加国内可访问的试用网址吧。

### ISSUE THREAD

**Issue by auendx** [Tencent/Hunyuan3D-1#2]
https://huggingface.co/tencent/Hunyuan3D-1

这个网址国内已经被禁了，请后续的开源项目都增加国内可以访问的试用平台网址吧。中国人自己的项目， 国内自己人却访问不了，麻烦你们了。

**Comment by HuiwenShi** [comment]
可以试试 HF_ENDPOINT=https://hf-mirror.com huggingface-cli download tencent/Hunyuan3D-1 --local-dir ./weights

**Comment by HuiwenShi** [comment]
https://hf-mirror.com/tencent/Hunyuan3D-1
