### ISSUE TITLE
An huggingface space is available.

### ISSUE THREAD

**Issue by darkon12** [Tencent/Hunyuan3D-1#25]
If you wanna try it without too much hassle:
https://huggingface.co/spaces/gokaygokay/Hunyuan3D-1.0

**Comment by darkon12** [comment]
Try tencent own:
https://huggingface.co/spaces/tencent/Hunyuan3D-1
Worked for me.

**Comment by realisticdreamer114514** [comment]
> Try tencent own: https://huggingface.co/spaces/tencent/Hunyuan3D-1 Worked for me.

The multi-view image the space does is far worse than what my local repo would do (something to do with image uploads? Lite model being used?), even if I can't go thru 'views to mesh' at all locally.
