### ISSUE TITLE
这个运行起来要多少内存，24G跑不起来吗？

### ISSUE THREAD

**Issue by papandadj** [Tencent/Hunyuan3D-1#28]
<img width="1026" alt="image" src="https://github.com/user-attachments/assets/657390fc-1693-4f1b-a6ae-a921499f17a8">
 python3 app.py --save_memory 这样启动的？

**Comment by supersyz** [comment]
能，20G可以跑



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年11月8日(周五) 晚上6:10
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [Tencent/Hunyuan3D-1] 这个运行起来要多少内存，24G跑不起来吗？ (Issue #28)




 image.png (view on web)  python3 app.py --save_memory 这样启动的？

**Comment by Wi-sc** [comment]
You can try to load the model one by one.
