### ISSUE TITLE
请问这个可以生成stl格式，用于3d打印的模型嘛？

### ISSUE THREAD

**Issue by ffli** [Tencent/Hunyuan3D-1#32]
你好，请问这个本地模型如何生成stl格式模型，
1.我本地部署跑起来之后，只看到有obj， glb格式模型可以预览和下载。
2.本地测试用demo里的图片生成3d模型，粗糙度感觉比较大，如何修改参数可以使生成模型更精致？
以下是我生成的模型：
![cha](https://github.com/user-attachments/assets/fcf7cf04-80b5-4cdc-866a-887b79536be0)
![panda](https://github.com/user-attachments/assets/b9c742af-4ab4-48aa-8902-85cd68daa49f)

**Comment by Wi-sc** [comment]
Thanks for your interest. If you want to print it, you may need to convert the shape into STL format using third-party software. And if you want a more detailed shape, you can increase the resolution setting.

**Comment by ffli** [comment]
The resolution is the source picture?The generated model is 90000 faces, i think is a high resolution, others with 20000 faces is more active than this. And if i check the texture mapping option, the generation will be error.
