### ISSUE TITLE
Pipelines loaded with `dtype=torch.float16` cannot run with `cpu` device

### ISSUE THREAD

**Issue by yincangshiwei** [Tencent/Hunyuan3D-1#33]
启动使用了--save_memory参数，让他加载到cpu那里，但生成obj的时候出现下面错误：
Pipelines loaded with `dtype=torch.float16` cannot run with `cpu` device. It is not recommended to move them to `cpu` as running them will fail. Please make sure to use an accelerator to run the pipeline in inference, due to the lack of support for`float16` operations on this device in PyTorch. Please, remove the `torch_dtype=torch.float16` argument, or use another device for inference.
![image](https://github.com/user-attachments/assets/225751e8-88a5-4f09-92c0-def67021a73a)

**Comment by HuiwenShi** [comment]
We have updated the code. Please clone it again and run it. If you encounter any errors, kindly share the console output here.
