### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by qtdslly** [Tencent/Hunyuan3D-1#35]
![b](https://github.com/user-attachments/assets/63a08b3f-5afb-430a-9c7c-9ebe8bc2a091)
![a](https://github.com/user-attachments/assets/3c1074bd-4270-483e-b297-c82fed71ad2b)
can't create obj or glb file，who can help me

**Comment by qtdslly** [comment]
问题已解决，应该是软件版本的问题，我是在gpuez.com上租的实例，更换镜像后重新部署下OK了，镜像版本是
![cc](https://github.com/user-attachments/assets/6731880e-8881-4da0-aa9f-6d083586919f)
所有的目标文件都可以生成，过程挺流畅，执行bash env_install.sh时，git clone可能会超时，多执行几次就OK了。
下面是实际的效果
![aa](https://github.com/user-attachments/assets/332572cf-e777-410b-8701-50ed52b9fa24)
![bb](https://github.com/user-attachments/assets/d20fd8bc-8e33-490c-be54-8d4ee27f6e73)

**Comment by dongjunyi24** [comment]
debug后发现是因为Hunyuan3D-1/svrm/ldm/models/svrm.py这个文件中在import open3d时缺少libX11和libXext，可以使用conda安装，如果还是找不到，可以使用sys.path.append把搜索路径添加上去就解决了
