### ISSUE TITLE
speed of the generation

### ISSUE THREAD

**Issue by shudct** [Tencent/Hunyuan3D-1#36]
Thanks for the wonderful work!
I have reproduced the generation on 4090, however the speed may different with the README.
![image](https://github.com/user-attachments/assets/098c1571-279f-4d6d-b8b8-2bf5c8cdffd4)

command: 
python3 main.py     --image_prompt ./demos/example_002.png     --save_folder ./outputs/test1/     --max_faces_num 90000     --do_texture_mapping   --use_lite

Is this normal?

**Comment by HuiwenShi** [comment]
The shortest inference time refers to the process from a single image to a vertex shading mesh, which we tested on the A100
