### ISSUE TITLE
Why did it take nearly two hours to generate just one image, with GPU usage at 100%? Is this normal?

### ISSUE THREAD

**Issue by o-zero-o** [Tencent/Hunyuan3D-1#39]
Why did it take nearly two hours to generate just one image, with GPU usage at 100%? Is this normal?
![img_v3_02gk_55b18c49-c8a4-4880-a82f-0a166fbca3dg](https://github.com/user-attachments/assets/3a17ac99-f41a-414f-b336-c8d2930a15e8)

**Comment by HuiwenShi** [comment]
The issue might be due to a large max_size setting in Gradio. Clicking multiple times causes subsequent tasks in the queue to be recorded as well. We've fixed max_size to 1. Please try cloning the repository again.
