### ISSUE TITLE
请教显存占用

### ISSUE THREAD

**Issue by supersyz** [Tencent/Hunyuan3D-1#4]
您好，看到readme说要40G显存左右，请问是对应lite还是std呀？24G显存没办法跑了吗TT
感谢大佬的开源！

**Comment by Commander-bao** [comment]
16G显存已经爆炸了

**Comment by HuiwenShi** [comment]
When the GPU memory is not enough, one way is to try to split the three modules in the process and run each module separately. We will optimize this area and release the code in the future

**Comment by HuiwenShi** [comment]
When the GPU memory is not enough, one way is to try to split the three modules in the process and run each module separately. We will optimize this and release the code in the future.

**Comment by Phrixus2023** [comment]
我也是只能出图，生成3D模型最精简的lite模型显存都爆炸了，我还是4090未阉割版

**Comment by Commander-bao** [comment]
> When the GPU memory is not enough, one way is to try to split the three modules in the process and run each module separately. We will optimize this and release the code in the future.

Thank you very much! I have modified the code, and now I am able to generate 3D models with my GPU.
